version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: manager_bot_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XXxx112233445566
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - manager_bot_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  manager_bot_pgdata:
